package com.artifactcomparator.artifact_comparator_backend.Enums;

public enum NotificationTypes {
    ACCEPTED_TO_STUDY_PARTICIPANT,
    INVITATION_TO_STUDY_PARTICIPANT,
    WAITING_FOR_QUIZ_APPROVAL_RESEARCHER,
    STUDY_REPORTED_ACCEPTED_RESEARCHER,
    STUDY_BLOCKED_RESEARCHER,
    STUDY_COMPLETED_BY_ALL_PARTICIPANTS_RESEARCHER,
    INVITATION_TO_STUDY_REVIEWER,
    INVITATION_TO_STUDY_RESEARCHER,
    USER_INFO_CHANGED_BY_ADMIN_FORALL
}